#!/bin/bash

#clear old ones. Regenerate every time
rm -rf _posts/Thumbnails/*

FILES=img/photos/thumbnails/*.jpg

for i in $FILES
    do
        temp=${i##*/}
        temp_2=${temp%.jpg}
        echo "---
layout: default
categories: Thumbnails
large_url: /photos/2017/01/01/$temp_2.html
full_url: /full/2017/01/01/$temp_2.html
picture: $i
---" > _posts/Thumbnails/2017-01-01-$temp_2.markdown
    done
