deploy:
  only: 
    - master
  script:
    - rsync -avz _site/* root@blog.doug-skinner.com:/var/www/html/.
    - rsync -avz _site/* root@blog2.doug-skinner.com:/var/www/html/.
    - rsync -avz _site/* root@blog3.doug-skinner.com:/var/www/html/.
