#!/bin/bash

#clear old ones. Regenerate every time
rm -rf _posts/Thumbnails/*

FILES=img/photos/thumbnails/*.jpg

for i in $FILES
    do
        date=$(sudo mdls $i | grep 'kMDItemInterestingDate_Ranking' | awk '{print $3}' | tr -d '\n')
        temp=${i##*/}
        temp_2=${temp%.jpg}
        echo "---
layout: default
categories: Thumbnails
tags: Photos
picture: $i
---" > _posts/Thumbnails/$date-$temp_2.markdown
    done
